### PR TITLE
Change activity to context

### LINKED ISSUE #15: Signature of AndroidTransloadit::newAssembly should be updated (Context instead of Activity) to enable uploads through services and workers
I'm pretty sure the method can be implemented using only the application context (a Context object, which is a superclass of Activity).

Current signature:
`public AndroidAsyncAssembly newAssembly(com.transloadit.sdk.async.AssemblyProgressListener listener, android.app.Activity activity);`

Desired signature:
`public AndroidAsyncAssembly newAssembly(com.transloadit.sdk.async.AssemblyProgressListener listener, android.content.Context context);`

Having to provide an Activity is really problematic, as activities are only available when the user is interacting with the app. Therefore I cannot provide an activity from a worker, which I'd like to use in order to offer my users a delayed upload (so they can select their files offline and have the worker upload them afterward when they are back online). I cannot provide an activity either from a service, from which I handle failed downloads (and from which I'd also like to handle failed uploads).

### PR DESCRIPTION
**Pull request by cdr-chakotay**
Closes #15

### CODE REVIEW

**Review by Acconut — APPROVED** [review]
Thanks!

**Comment by Acconut** [comment]
I think we can release this as a non-breaking change because every `Activity` is a `Context`, isn't it? So this should not cause many issues unless people are using reflection or so. What do you think?

**Comment by cdr-chakotay** [comment]
> I think we can release this as a non-breaking change because every `Activity` is a `Context`, isn't it? So this should not cause many issues unless people are using reflection or so. What do you think?

Thought that as well, already tested it yesterday with the example app as you might noticed ;)

**Comment by patricks-dev** [comment]
AFAIK your changes should be perfectly fine... Thank you very much!

**Comment by cdr-chakotay** [comment]
You are welcome :)

**Pull request merged**
